export enum TextEditorToolbarButtons {
    Bold = 'bold',
    Italic = 'italic',
    Underline = 'underline',
    StrikeThrough = 'strikeThrough',
    Subscript = 'subscript',
    Superscript = 'superscript',
    InsertTable = 'insertTable',
    VerticalSeparator = '|',
    HorizontalSeparator = '-',
    ParagraphFormat = 'paragraphFormat',
    Align = 'align',
    Undo = 'undo',
    Redo = 'redo',
    Html = 'html',
    FontFamily = 'fontFamily',
    FontSize = 'fontSize',
    TextColor = 'textColor',
    BackgroundColor = 'backgroundColor',
    InlineClass = 'inlineClass',
    InlineStyle = 'inlineStyle',
    ClearFormatting = 'clearFormatting',
    InsertLink = 'insertLink',
    InsertImage = 'insertImage',
    InsertVideo = 'insertVideo',
    Emoticons = 'emoticons',
    FontAwesome = 'fontAwesome',
    SpecialCharacters = 'specialCharacters',
    Embedly = 'embedly',
    InsertFile = 'insertFile',
    InsertHr = 'insertHR',
    Fullscreen = 'fullscreen',
    Print = 'print',
    GetPDF = 'getPDF',
    Spellchecker = 'spellChecker',
    SelectAll = 'selectAll',
    Outdent = 'outdent',
    Indent = 'indent'
}

export const defaultTextEditorToolbarButtons =  [
    TextEditorToolbarButtons.Bold,
    TextEditorToolbarButtons.Italic,
    TextEditorToolbarButtons.Underline,
    TextEditorToolbarButtons.StrikeThrough,
    TextEditorToolbarButtons.Subscript,
    TextEditorToolbarButtons.Superscript,
    TextEditorToolbarButtons.InsertTable,
    TextEditorToolbarButtons.VerticalSeparator,
    TextEditorToolbarButtons.ParagraphFormat,
    TextEditorToolbarButtons.Align,
    TextEditorToolbarButtons.Undo,
    TextEditorToolbarButtons.Redo
];
